import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import IconsSidebar from "@/components/customComponets/IconsSidebar";
import LayoutWrapper from "@/components/customComponets/LayoutWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"font-sora"}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
